# Generated by Django 4.0.4 on 2022-04-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dafe_of_birth',
            new_name='date_of_birth',
        ),
    ]
